### PR TITLE
IBX-3639: As an Editor I'd like use facets to filter global search results

### PR DESCRIPTION
**Pull request by adamwojs**
| Question      | Answer
| ------------- | ---
| Tickets       |  [IBX-6339](https://issues.ibexa.co/browse/IBX-6339) 
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | yes
| License       | [GPL-2.0](https://github.com/ibexa/search/blob/main/LICENSE)

#### Checklist:
- [x] Implement tests
- [x] Coding standards (`$ composer fix-cs`)

### CODE REVIEW

**Review by ViniTou — APPROVED** [review]

**Review by konradoboza — APPROVED** [review]

**Comment by bogusez** [comment]
@adamwojs searching for content name i global search cases an exception with error code 500
The issue occurred on legacy search engine.

Screenshot 2023-09-06 at 09 31 00

**Comment by adamwojs** [comment]
@bogusez You can continue testing, issue should be fixed now.

**Comment by bogusez** [comment]
@adamwojs when I do a reindex and then I open page {host}/admin/search an error 500 occurs (Legacy search engine).

Screenshot 2023-09-11 at 11 13 28

**Comment by adamwojs** [comment]
@bogusez Fixed in https://github.com/ibexa/admin-ui/pull/871/commits/786eec064f401d3840ce3bf8a1c3795024f999c3. You can continue testing.

**Comment by bogusez** [comment]
Regression tests passed:
https://github.com/ibexa/headless/pull/17
https://github.com/ibexa/experience/pull/233
https://github.com/ibexa/commerce/pull/377

**Review by bogusez — APPROVED** [review]

**Pull request merged**
